### ISSUE TITLE
Notion Enhancer Infinite Loading in windows 

### ISSUE THREAD

**Issue by MahmoudKhalefa2020** [notion-enhancer/notion-repackaged#129]
I Installed Notion and Notion Enhancer and Notion enhancer Extension, Notion enhancer it's working on Notion web site but when I open Notion enhancer desktop its Infinite loading, I don't know what I should do
![loading](https://github.com/notion-enhancer/notion-repackaged/assets/82944257/adc0477c-619c-4509-ac4c-69f8a5e2a2d0)

**Comment by xmha97** [comment]
I have this problem too :(
@dragonwocky Please fix this issue.

**Comment by hersheysmcflurry** [comment]
@MahmoudKhalefa2020 @xmha97 the NE app is being reworked. a solution for the loading issue has already been posted in #116. you can try fixing it yourself. otherwise you'll have to use the browser version or wait for the developer to release the updated app when it's ready.

**Comment by MahmoudKhalefa2020** [comment]
![image](https://github.com/notion-enhancer/notion-repackaged/assets/82944257/ed355695-54ca-4f4a-a18c-a14554743191)

**Comment by MahmoudKhalefa2020** [comment]
![image](https://github.com/notion-enhancer/notion-repackaged/assets/82944257/a6bfa513-c1c3-4c07-b7a7-8bde736168d0)

**Comment by dragonwocky** [comment]
Hi there @MahmoudKhalefa2020, these screenshots don't explain the trouble you're having very well and don't seem related to this particular issue either. As far as I can see, there's nothing in either of your screenshots that should be causing you significant troubles, they look mostly as-expected.

This issue has also been closed as a duplicate of #116, so any comments relating to it should be directed there, not here (unless you believe an issue has not yet been properly addressed, you generally shouldn't be commenting on closed issues). If your problem is unrelated to infinite loading, please create a new issue and explain what you're encountering in detail instead.

**Comment by MahmoudKhalefa2020** [comment]
I Tom , this issue related infinite loop , I installed Notion Enhancer and
open console and I find this errors cause infinite loop and I don't know
How I can solve it

‫في الجمعة، 26 أبريل 2024 في 3:53 ص تمت كتابة ما يلي بواسطة ‪Tom‬‏ <‪
***@***.***‬‏>:‬
