### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by gruvw** [notion-enhancer/notion-repackaged#28]
Is there any plan to add offline mode like [notion-linux](https://github.com/davidbailey00/notion-linux) ?

**Comment by jamezrin** [comment]
The offline mode is already there, and as far as I know it is native to notion. I just checked and it is working properly for me. What are you experiencing instead? How does it differ to notion-linux?

**Comment by gruvw** [comment]
Well I tried to install the appimage and the Deb file but both of them gave me a message (something like please connect to network before using) when opening the app while in air plane mode...

This is not happening with the normal notion-linux and still not happening after installing notion enhancer with npm.

**Comment by jamezrin** [comment]
I'm pretty sure it's because notion-linux is based off 2.0.11, but we target 2.0.16 instead, which might have introduced that message.

If you load notion and then you disconnect you will still be able to view already cached pages, that's the offline support we have.

Also, have in mind that notion-linux is using storing the cache in one place and notion-repackaged is storing it in a different one.

**Comment by gruvw** [comment]
Ok but it doesn't work for me.

I downloaded and ran the appimage, logged into my account and browsed through my different pages. Then I quit the app and turn on airplane mode. When I launch the app again this message appears.

**Comment by jamezrin** [comment]
Yeah, I don't think we are going to try to override that behavior in the long term. If notion released 2.0.16 with that behavior, it's for a reason.
