### ISSUE TITLE
The program is not really closing with "X"

### ISSUE THREAD

**Issue by albertopasqualetto** [notion-enhancer/notion-repackaged#36]
When closing the window it doesn't really close the program, instead it used 32% of cpu (in 2 processes).

**Comment by jamezrin** [comment]
The fact that when clicking the "X" it doesn't close the program is something that works as intended. Instead of closing the program it minimizes, and you can toggle the visibility via the taskbar icon.

And regarding the CPU usage, the next version fixes an infinite loop that caused high CPU and memory usage. Please try the new version (releasing in a few minutes). Beware that it's normal that notion uses multiple processes, it's how electron (and chromium) works.

**Comment by albertopasqualetto** [comment]
Well but I set that pressing the X should close it, in fact I have nothing in the taskbar.

Anyway thanks for the new release; I will test it ASAP and then I'll update the issue.

**Comment by EliWimmer** [comment]
To clarify, he did not mean taskbar, but the system tray. By default it closes to the system tray, but this option can be changed in the enhancements menu.

**Comment by albertopasqualetto** [comment]
Sorry, also I meant that and I disabled that setting.
![image](https://user-images.githubusercontent.com/39854348/134466195-f1e7aad7-195d-43d2-a2bd-e765d070e817.png)

**Comment by albertopasqualetto** [comment]
I tried the new update and now, without changing any setting, it really closes with "X", so the problem seems resolved.
