### ISSUE TITLE
Starting notion when it's already in the background crashes the new process

### ISSUE THREAD

**Issue by juliavdkris** [notion-enhancer/notion-repackaged#38]
Starting notion when it's already running in the background crashes the new process, instead of just showing the window for the already running instance

This is on Arch using the [notion-app-enhanced](https://aur.archlinux.org/packages/notion-app-enhanced/) AUR package. stdout and stderr output attached, if you need any other logs/info please let me know! :)

[log.txt](https://github.com/notion-enhancer/notion-repackaged/files/7229518/log.txt)

**Comment by jamezrin** [comment]
That's strange... what DE/WM are you using? I just tried it and I got two windows, but no crash.

The error that is in the log (focused_window.isMaximized is not a function) you provided shouldn't cause a crash, it happens but the app should work ok anyway.

**Comment by juliavdkris** [comment]
Yeah it seemed like a weird error to me as well. I'm on GNOME 40.4.0 (X11, because Nvidia hates me)

**Comment by juliavdkris** [comment]
In other news: I just tried it again and it doesn't crash anymore ¯\\\_(ツ)_/¯

It indeed just opens two instances now. Would still be really nice if this would toggle visibility on the already running instance though. Clicking on the tray icon -> "toggle visibility" is a bit of a hassle :)

**Comment by jamezrin** [comment]
Yeah, I also think that, but it seems like the tray icon handles it well (if two windows are open and you toggle visibility, the two windows are hidden, and when you toggle again, both windows show), so maybe it works as intended, I don't know. 
@dragonwocky what do you think?

**Comment by juliavdkris** [comment]
Ok nevermind, I've been able to reproduce the bug! It only launches a new window if the previous instance still has a window open. If the previous instance is hidden, launching a new instance will crash.

But I also just noticed there's actually a hotkey to toggle visibility, which makes toggling via the tray a lot less of a hassle :)

(Though maybe the crash is actually related to that? Something about one of the windows being hidden while the other one is being shown breaking the toggle functionality?)

**Comment by dragonwocky** [comment]
I'm not exactly sure why it only crashed when the other window is hidden, but yes, it's a bug from poor design. That specific feature was originally built with the tray/hotkey behaviour as the one that controlled everything else and attempting to relaunch the app will either a) do nothing if it's hidden or b) add a new window - which works great and as intended on Windows, but has been playing up with other WMs on MacOS and Linux. I plan to make it so that the shortcut has the same effect as the tray, and just toggles the windows rather than creating new ones, and if you do need a second window you will have to use tabs or `ctrl+shift+n`.

**Comment by juliavdkris** [comment]
Ahhh, doing nothing if the first window is hidden is intended behavior? In that case what I'm seeing isn't a crash, but just the new process exiting without opening a new window or toggling visibility on the existing one (as I expected).
