### ISSUE TITLE
Sync not completing

### ISSUE THREAD

**Issue by king-11** [notion-enhancer/notion-repackaged#40]
I have had this experience several times where I type in content and that content stops syncing back to notion, the saving icon keeps on skipping but never completes its task eventually have to close the app and all progress is lost.

**Comment by dragonwocky** [comment]
Strange. What platform are you on? Can you confirm that this is caused by the enhancer? (Uninstall the enhancer and attempt to reproduce the issue on normal Notion.) It sounds more possible/likely that this is a bug with Notion itself or caused by poor internet. It could even be caused by a firewall somewhere in your system.

**Comment by king-11** [comment]
Just checked I think the issue is with notion-app itself cause it is not under development now. I will close the issue hoping for a new maintainer to join and develop the app

**Comment by dragonwocky** [comment]
@king-11 which notion-app are you using? If it's https://aur.archlinux.org/packages/notion-app/, then that is from this repository and should work. Otherwise, notion-repackaged is currently the only maintained true-port of Notion to Linux. The other projects are discontinued/out-of-date - new maintainers probably aren't going to be joining them.

Try installing from https://github.com/notion-enhancer/notion-repackaged/releases/tag/v2.0.16-5 (there are .deb, .AppImage, .rpm, and other installable files there).

**Comment by king-11** [comment]
I am using the AUR notion-app package

**Comment by jamezrin** [comment]
> I am using the AUR notion-app package

What gives you the impression it's not being maintained anymore? As @dragonwocky said, that PKGBUILD uses the releases from here. The PKGBUILD doesn't need to update on every new revision as there are changes that only apply to the enhanced version. That's all to say that the AUR package is still  maintained.

**Comment by king-11** [comment]
@jamezrin 😅 I was under presumption that its another package and you guys only maintain the enhanced one. Should have read more In view of that I wil reopen the issue for tracking

**Comment by king-11** [comment]
@dragonwocky there seems to be no firewall enabled by me and the internet connection might be an issue at times but shouldn't the app re try after getting back online
