### ISSUE TITLE
Add option to open silently?

### ISSUE THREAD

**Issue by soumitradev** [notion-enhancer/notion-repackaged#57]
I know there is an option in the enhancer to open it minimized, but it'd be really helpful if it could take an option like `--silent` and open minimized instead of setting it to open minimized all the time. It could be used to open Notion on startup silently, and anytime the user opens it, it would open completely.

**Comment by dragonwocky** [comment]
@soumitradev silent open on startup is already planned, but as a separate option built into the enhancer called "open minimised on startup" (or something similar) rather than a CLI option. CLI options on startup generally won't be added as something intended for users to directly interact with, as its not something that would be simple for the average non-techy person to do. The enhancer does require some technical knowledge at the moment, but the goal is to reduce that rather than increase it.
