### ISSUE TITLE
High RAM usage 

### ISSUE THREAD

**Issue by Akash-Sharma-1** [notion-enhancer/notion-repackaged#69]
Notion Repackaged starts using a lot of RAM as compared to native Notion application.
I had only 1 tab open and Notion Repackage was taking about 4-5 GBs of RAM.

Not sure what is causing this.
Could you please help me with this ?

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/desktop/issues/333

**Comment by Akash-Sharma-1** [comment]
Thanks @dragonwocky for the help :)

Just to point out, I am not very sure but it looks to me that  Notion Repackaged application was taking more RAM than Notion enhancer's npm package usage in Native Notion. 

Will be following the known bug issue that you mentioned 👍
Thanks again :)

**Comment by dragonwocky** [comment]
@Akash-Sharma-1 notion-repackaged doesn't have any extra features over the npm package (just bugfixes), nor is the memory leak consistent in the amount it takes up (sometimes only 1 or 2 GB, sometimes 4 or 5, sometimes 20). Plus that can't really be compared since the npm package is currently very broken.

Thanks for the extra info anyway, though!

**Comment by Akash-Sharma-1** [comment]
Makes sense , I agree - The memory leak doesn't looks like its consistent 😅
Thanks again :)
