### ISSUE TITLE
Question regarding app size

### ISSUE THREAD

**Issue by specter78** [notion-enhancer/notion-repackaged#77]
How come this app is around 300 mb when the official app is >450 mb on macOS? Since you are adding code to it, surely it must be at least as big as official app.

What is the reason?

**Comment by dragonwocky** [comment]
@specter78 honestly, I don't know, that does sound pretty strange.

As far as we know, since it's an Electron app, it's the same app running on every platform, just packaged slightly differently.
notion-repackaged is built for all platforms from the source extracted from the Windows app (which is around 340 MB vanilla), which should be fine - I've read through that source and it contains code that looks specifically tailored for macOS.

It's possible that there are some extra assets packaged with the macOS app or something? None of us are on macOS, so it's not something we've checked/noticed. I don't think it's a bug, but it's definitely something interesting to look into, so I've marked it as a question and we can just leave the issue open until we figure it out.

I do plan to do some testing on a family member's macOS soonish, so I might have a look then, otherwise if you want to look for yourself: if you go into `/Applications/Notion.app` there'll probably be a whole bunch of things. Find either a folder named `app` or a file named `app.asar` and check the size of that - that file/folder contains the app source that's shared between platforms. On Windows, it's only around 180 MB for me (160 MB less than the whole app - I'm guessing that's made up by the binaries the app depends on to run).

Alternate possibility: is this copy of the official app vanilla, or is it one that has been enhanced (currently or previously) via the notion-enhancer CLI? If it has been enhanced, then the `app.asar`/`app` will have been duplicated as a backup. It could be that those extra MB are coming from that backup (it'd be a file or folder named `app.asar.bak` or `app.bak`), which wouldn't be present in the notion-repackaged build.

**Comment by specter78** [comment]
@dragonwocky 

<img width="344" alt="original" src="https://user-images.githubusercontent.com/40606342/147479165-270b51dd-9d17-4d96-8699-97109c725d30.png">

<img width="327" alt="enhanced" src="https://user-images.githubusercontent.com/40606342/147479213-edcc8f4d-f880-4696-b4ef-4e6840a6c9e3.png">

Also, the official version is v2.0.19 and the enhanced version is based on 2.0.16 (so that needs updating).

I looked into the app. The size difference is majorly in `node_modules` folder with the official version around 280mb and the enhanced version around 120mb.

**Comment by specter78** [comment]
Also since you are anyway extracting the source, I think you also also reduce/remove requests to Notion that are used to track user activity.

**Comment by dragonwocky** [comment]
I see.

notion-enhancer v0.10.x only works on 2.0.16, which is why notion-repackaged is built from 2.0.16. notion-enhancer v0.11.0 will be built from 2.0.18 (the latest for all versions other than the Intel macOS build). Note that this is only the app version, which is separate from the Notion client version (the same Notion client is loaded with the same updates/features regardless of which app version you use).

`node_modules` is just the dependency cache- we refresh it to make sure that only the right dependencies for the target platform are included in it, Notion may be including some extra dev dependencies or multi-platform versions of the dependencies. It having a smaller size is nothing to be concerned about.

We aren't intentionally doing anything related to user activity tracking, but if it's being disabled/removing then that's not really a bit problem.

**Comment by jamezrin** [comment]
Honestly, I also don't know. As @dragonwocky said, we take the official Windows build, unpack it, apply the enhancer to these sources and rebuild the app.

I could attribute the difference in size between the apps to the builder, which is `electron-builder`, maybe our version (always latest) has improvements that the version that they build with doesn't have? Especially the electron runtime and its libraries that are included in the app.

@specter78 the difference in the `node_modules` can be also attributed to the fact that we might be using a newer node.js version and it's toolchain. We are installing the `node_modules` that they declare in the `package.json`. I highly doubt we are accidentally removing user activity tracking, I'm pretty sure that's backed in into the Notion (the web app itself, not the electron code)

**Comment by specter78** [comment]
@dragonwocky @jamezrin Sorry there has been a typo in my previous comment. What I meant is that enhanced version "should remove" tracking, not that it removes tracking. And since you automate the build, it should be relatively easy (like what https://github.com/Eloston/ungoogled-chromium/ does).

**Comment by dragonwocky** [comment]
@specter78 I see.

There is a big difference though that changes it from "relatively easy" to "relatively impossible".
- Chromium is an app in its own right. You can just remove parts of the app, and they're gone.
- The Notion app is an Electron app that loads the Notion website/client, which we can't remove parts from, only
  overwrite parts of. Tracking is part of the Notion web client, not the app. We can't remove or disable tracking.

Whether the build is automated or not doesn't change that. Removing tracking from Notion would be equivalent to trying to remove tracking from the Google website, not equivalent to removing tracking from the Chromium app.
