### ISSUE TITLE
Notion-Enhanced 2.0.18-1 only launches vanilla Notion

### ISSUE THREAD

**Issue by Glint-Eye** [notion-enhancer/notion-repackaged#80]
**What is happening?**

After the update to 2.0.18-1 (notion-enhancer v0.11.0) Notion-Enhanced launches vanilla Notion. No Sidebar option in Notion is shown to configure the Enhancer. No panel icon to configure the Enhancer is shown either (that's how it worked for me pre 2.0.18-1 (notion-enhancer v0.11.0))

I have tried the installation form the added repository notion-app-enhanced
and i've tried the AppImage version. Both only start Vanilla Notion

**Operating system/browser name & version:**

Pop OS 21.10

**notion-enhancer and/or notion-repackaged version:**

Notion-Enhanced 2.0.18-1 (notion-enhancer v0.11.0)

**Comment by honear** [comment]
This was just addressed in the discord :)
Dragonwocky: 

❗ _Previous/existing notion-enhancer users: The new version of the notion-enhancer handles storing local configuration differently to previous versions. You may need to delete a folder named .notion-enhancer within your home/user folder in order to use the update.

The update uses a different storage schema and has overhauled mod options, so whether you delete that folder or not, your configurations will be reset by the update. (It's worth it, I promise!)_

**Comment by dragonwocky** [comment]
thanks @honear :)

@Glint-Eye if the bug persists after trying that fix, please reopen the issue and add screenshots of the contents of the console (press `ctrl+shift+i` within notion & then go to the "console" tab)

**Comment by Glint-Eye** [comment]
works fine for me now.

thx for the quick help @honear

**Comment by pintomau** [comment]
A hint for the devs.

I installed this on a brand new windows install and the notion-enhancer option did not appear in the side bar until closing and opening a few times.

I was in the process of opening the console to take some screenshots after closing and reopening, when I noticed that I now do see the option.

**Comment by dragonwocky** [comment]
@pintomau for security reasons the notion-enhancer does not appear if you the app launched without being logged into Notion yet. I will add a note about that to the website, though.
